# Generated by Django 5.2.5 on 2025-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettransferrequest',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/images/'),
        ),
        migrations.AlterField(
            model_name='tickettransferrequest',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/files/'),
        ),
    ]
