# Generated by Django 5.2.5 on 2025-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getticket', '0002_tickettransferrequest_ticket_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettransferrequest',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
