# Generated by Django 5.2.5 on 2025-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getticket', '0003_tickettransferrequest_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaystaff',
            name='role',
            field=models.CharField(choices=[('HEAD', 'Ticket Booking Head'), ('CLERK', 'Clerk'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='railwaystaff',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
